name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "yarn"
      run: yarn

    - name: "yarn build"
      run: yarn build

    - name: "yarn test"
      run: yarn test
